name: Labeler

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  label:
    name: Apply Labels to Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Apply Labels Based on PR Changes
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
